.\" Copyright (c) 2011 Jean Schurger
.\" Man page for gde2-calc
.TH GDE2-CALC-CMD 1 "1 February 2014" "GDE2 Desktop Environment" "General Manual"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
gde2-calc-cmd \- A console calculator for the GDE2 Desktop Environment.
.SH "SYNOPSIS"
\fBgde2-calc-cmd\fR
.SH "DESCRIPTION"
\fBgde2-calc-cmd\fR is the console version of \fBgde2-calc\fR, the calculator for the GDE2 Desktop Environment.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/gde2-desktop/gde2-calc/issues
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.gde2-desktop.org/docs
.P
.BR gde2-calc (1)
